export const data1 = [
    {
        team_name: "AlphaTeam",
        title: "Task A",
        id: "678903333",
        tags: ["urgent", "backend"],
        assignees: ["Alice", "Bob"],
        columnId: "column1",
    },
    {
        team_name: "BetaSquad",
        title: "Task B",
        id: "23456",
        tags: ["frontend", "review"],
        assignees: ["Charlie", "David"],
        columnId: "column1",
    },
    {
        team_name: "GammaGroup",
        title: "Task C",
        id: "345672354",
        tags: ["testing", "documentation"],
        assignees: ["Eve", "Frank"],
        columnId: "column1",
    },
    {
        team_name: "DeltaDivision",
        title: "Task D",
        id: "456782354",
        tags: ["deployment", "urgent"],
        assignees: ["Grace", "Hank"],
        columnId: "column1",
    },
    {
        team_name: "EpsilonUnit",
        title: "Task E",
        id: "567823424",
        tags: ["design", "ux"],
        assignees: ["Ivy", "Jack"],
        columnId: "column1",
    },
];

export const data2 = [
    {
        team_name: "ZetaTeam",
        title: "Task Z",
        id: "78901",
        tags: ["security", "urgent"],
        assignees: ["Alice", "Eve"],
        columnId: "column2",
    },
    {
        team_name: "ThetaSquad",
        title: "Task Y",
        id: "89012",
        tags: ["research", "backend"],
        assignees: ["Bob", "Frank"],
        columnId: "column2",
    },
    {
        team_name: "IotaGroup",
        title: "Task X",
        id: "90123",
        tags: ["frontend", "design"],
        assignees: ["Charlie", "Grace"],
        columnId: "column2",
    },
    {
        team_name: "KappaDivision",
        title: "Task W",
        id: "01234",
        tags: ["documentation", "testing"],
        assignees: ["David", "Hank"],
        columnId: "column2",
    },
    {
        team_name: "LambdaUnit",
        title: "Task V",
        id: "12345",
        tags: ["deployment", "review"],
        assignees: ["Eve", "Ivy"],
        columnId: "column2",
    },
    {
        team_name: "MuTeam",
        title: "Task U",
        id: "23456555",
        tags: ["security", "backend"],
        assignees: ["Frank", "Jack"],
        columnId: "column2",
    },
    {
        team_name: "NuSquad",
        title: "Task T",
        id: "34567",
        tags: ["research", "frontend"],
        assignees: ["Grace", "Alice"],
        columnId: "column2",
    },
    {
        team_name: "XiGroup",
        title: "Task S",
        id: "45678",
        tags: ["design", "testing"],
        assignees: ["Hank", "Bob"],
        columnId: "column2",
    },
    {
        team_name: "OmicronDivision",
        title: "Task R",
        id: "56789",
        tags: ["documentation", "deployment"],
        assignees: ["Ivy", "Charlie"],
        columnId: "column2",
    },
    {
        team_name: "PiUnit",
        title: "Task Q",
        id: "67890",
        tags: ["review", "security"],
        assignees: ["Jack", "David"],
        columnId: "column2",
    },
];

export const data3 = [
    {
        team_name: "AlphaTeam",
        title: "Task A",
        id: "10001",
        tags: ["urgent", "backend"],
        assignees: ["Alice", "Bob"],
        columnId: "column3",
    },
    {
        team_name: "BetaSquad",
        title: "Task B",
        id: "10002",
        tags: ["frontend", "review"],
        assignees: ["Charlie", "David"],
        columnId: "column3",
    },
    {
        team_name: "GammaGroup",
        title: "Task C",
        id: "10003",
        tags: ["testing", "documentation"],
        assignees: ["Eve", "Frank"],
        columnId: "column3",
    },
    {
        team_name: "DeltaDivision",
        title: "Task D",
        id: "10004",
        tags: ["deployment", "urgent"],
        assignees: ["Grace", "Hank"],
        columnId: "column3",
    },
    {
        team_name: "EpsilonUnit",
        title: "Task E",
        id: "10005",
        tags: ["design", "ux"],
        assignees: ["Ivy", "Jack"],
        columnId: "column3",
    },
    {
        team_name: "ZetaTeam",
        title: "Task Z",
        id: "10006",
        tags: ["security", "urgent"],
        assignees: ["Alice", "Eve"],
        columnId: "column3",
    },
    {
        team_name: "ThetaSquad",
        title: "Task Y",
        id: "10007",
        tags: ["research", "backend"],
        assignees: ["Bob", "Frank"],
        columnId: "column3",
    },
    {
        team_name: "IotaGroup",
        title: "Task X",
        id: "10008",
        tags: ["frontend", "design"],
        assignees: ["Charlie", "Grace"],
        columnId: "column3",
    },
    {
        team_name: "KappaDivision",
        title: "Task W",
        id: "10009",
        tags: ["documentation", "testing"],
        assignees: ["David", "Hank"],
        columnId: "column3",
    },
    {
        team_name: "LambdaUnit",
        title: "Task V",
        id: "10010",
        tags: ["deployment", "review"],
        assignees: ["Eve", "Ivy"],
        columnId: "column3",
    },
    {
        team_name: "MuTeam",
        title: "Task U",
        id: "10011",
        tags: ["security", "backend"],
        assignees: ["Frank", "Jack"],
        columnId: "column3",
    },
    {
        team_name: "NuSquad",
        title: "Task T",
        id: "10012",
        tags: ["research", "frontend"],
        assignees: ["Grace", "Alice"],
        columnId: "column3",
    },
    {
        team_name: "XiGroup",
        title: "Task S",
        id: "10013",
        tags: ["design", "testing"],
        assignees: ["Hank", "Bob"],
        columnId: "column3",
    },
    {
        team_name: "OmicronDivision",
        title: "Task R",
        id: "10014",
        tags: ["documentation", "deployment"],
        assignees: ["Ivy", "Charlie"],
        columnId: "column3",
    },
    {
        team_name: "PiUnit",
        title: "Task Q",
        id: "10015",
        tags: ["review", "security"],
        assignees: ["Jack", "David"],
        columnId: "column3",
    },
    {
        team_name: "RhoTeam",
        title: "Task P",
        id: "10016",
        tags: ["urgent", "design"],
        assignees: ["Alice", "Eve"],
        columnId: "column3",
    },
    {
        team_name: "SigmaSquad",
        title: "Task O",
        id: "10017",
        tags: ["backend", "documentation"],
        assignees: ["Bob", "Frank"],
        columnId: "column3",
    },
    {
        team_name: "TauGroup",
        title: "Task N",
        id: "10018",
        tags: ["frontend", "testing"],
        assignees: ["Charlie", "Grace"],
        columnId: "column3",
    },
    {
        team_name: "UpsilonDivision",
        title: "Task M",
        id: "10019",
        tags: ["deployment", "ux"],
        assignees: ["David", "Hank"],
        columnId: "column3",
    },
    {
        team_name: "PhiUnit",
        title: "Task L",
        id: "10020",
        tags: ["design", "review"],
        assignees: ["Eve", "Ivy"],
        columnId: "column3",
    },
    {
        team_name: "ChiTeam",
        title: "Task K",
        id: "10021",
        tags: ["security", "frontend"],
        assignees: ["Frank", "Jack"],
        columnId: "column3",
    },
    {
        team_name: "PsiSquad",
        title: "Task J",
        id: "10022",
        tags: ["research", "ux"],
        assignees: ["Grace", "Alice"],
        columnId: "column3",
    },
];

export const data4 = [
    {
        team_name: "OmegaGroup",
        title: "Task I",
        id: "10023",
        tags: ["testing", "deployment"],
        assignees: ["Hank", "Bob"],
        columnId: "column4",
    },
    {
        team_name: "AlphaDivision",
        title: "Task H",
        id: "10024",
        tags: ["documentation", "design"],
        assignees: ["Ivy", "Charlie"],
        columnId: "column4",
    },
    {
        team_name: "BetaUnit",
        title: "Task G",
        id: "10025",
        tags: ["review", "backend"],
        assignees: ["Jack", "David"],
        columnId: "column4",
    },
];

export const columnData = [
    {
        id: "column1",
        name: "NOT STARTED",
        data: data1,
    },
    {
        id: "column2",
        name: "IN PROGRESS",
        data: data2,
    },
    {
        id: "column3",
        name: "UNDER REVIEW",
        data: data3,
    },
    {
        id: "column4",
        name: "SHIPPED",
        data: data4,
    },
];
